import Head from 'next/head'
import React from 'react'

const About = () => {
    return (
        <div>
            <Head>
                <title>Matti's store | About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            this is the about page
        </div>
    )
}

export default About
