import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router';
import Head from 'next/head';

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import axios from 'axios';
const ForgetPassword = () => {
    const router = new useRouter();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    console.log(router.query.token);
    useEffect(() => {
        if (localStorage.getItem('myuser')) {
            router.push('/')
        }
    }, [])
    const handleInput = (e) => {
        if (e.target.name === 'email') {

            setEmail(e.target.value)
        }
        if (e.target.name === 'password') {

            setPassword(e.target.value)
        }

    }
    const handleSubmit = async (e) => {
        e.preventDefault();
        const data = {
            email, sendMail: true
        }
        const user = await axios.post(`${process.env.NEXT_PUBLIC_HOST}/api/forgetpassword`, { data });
        console.log(user);
        if (user.status === 200) {
            toast("Password set instruction have been sent to your email");
        } else {
            toast.error("Something went wrong");

        }
        console.log(email);
    }
    const handlePassChangeSubmit = async (e) => {
        e.preventDefault();
        const data = {
            password, sendMail: false
        }
        const user = await axios.post(`${process.env.NEXT_PUBLIC_HOST}/api/forgetpassword`, { data });
        console.log(user);
        if (user.status === 200) {
            toast("Passwor has been changed");
        } else {
            toast.error("Something went wrong");

        }
        console.log(password);
    }
    return (
        <div>
            <Head>
                <title>Matti's store | Forgot Password</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ToastContainer
                position="bottom-center"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
            />
            <div className="flex min-h-screen items-start justify-center mt-20 py-12 px-4 sm:px-6 lg:px-8">
                <div className="w-full max-w-md space-y-8">
                    <div>
                        <img className="mx-auto h-12 w-auto" src={'/ecommlogo.png'} alt="Your Company" />
                        <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Forgot Password</h2>
                        <p className="mt-2 text-center text-sm text-gray-600">
                            Or
                            <Link href={'/login'} className="font-medium text-indigo-600 hover:text-indigo-500"> Login in</Link>
                        </p>
                    </div>

                    {!router.query.token && <form onSubmit={handleSubmit} className="mt-8 space-y-6" >
                        <input type="hidden" name="remember" value="true" />
                        <div className="-space-y-px rounded-md shadow-sm">
                            <div>
                                <label htmlFor="emailaddress" className="sr-only">Email address</label>
                                <input onChange={handleInput} value={email} id="emailaddress" name="email" type="email" autoComplete="email" required className="relative block w-full rounded-t-md border-0 p-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="Email address" />
                            </div>

                        </div>



                        <div>
                            <button type="submit" className="group relative flex w-full justify-center rounded-md bg-indigo-600 py-2 px-3 text-sm font-semibold text-white hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">

                                Continue
                            </button>
                        </div>
                    </form>}
                    {router.query.token && <form onSubmit={handlePassChangeSubmit} className="mt-8 space-y-6" >
                        <input type="hidden" name="remember" value="true" />
                        <div className="-space-y-px rounded-md shadow-sm">
                            <div>
                                <label htmlFor="emailaddress" className="sr-only">Reset Password</label>
                                <input onChange={handleInput} value={password} id="emailaddress" name="password" type="password" autoComplete="password" required className="relative block w-full rounded-t-md border-0 p-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="Enter Password" />
                            </div>

                        </div>



                        <div>
                            <button type="submit" className="group relative flex w-full justify-center rounded-md bg-indigo-600 py-2 px-3 text-sm font-semibold text-white hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">

                                Continue
                            </button>
                        </div>
                    </form>}
                </div>
            </div>
        </div>
    )
}

export default ForgetPassword
